version: '3.7'
services:
  app:
    build:
      context: .
      target: build
    volumes:
      - ./:/go/app
    command: air
    ports:
      - 3001:3001
      - 2345:2345
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
  generator:
    build:
      context: .
      dockerfile: Dockerfile-generator
    volumes:
      - ./:/go/app
    tty: true
