development:
  dialect: mysql
  datasource: news:news_password@tcp(host.docker.internal:3309)/news?charset=utf8mb4&parseTime=True&loc=Local
production:
  dialect: mysql
  datasource: ${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${MYSQL_DATABASE}?charset=utf8mb4&parseTime=True&loc=Local
