// Code generated by SQLBoiler 4.1.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ArticleTags    string
	Articles       string
	GorpMigrations string
	Sites          string
	Tags           string
}{
	ArticleTags:    "article_tags",
	Articles:       "articles",
	GorpMigrations: "gorp_migrations",
	Sites:          "sites",
	Tags:           "tags",
}
